apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  template:
    spec:
      containers:
        - name: imx-fieldlab-woz
          image: imx-fieldlab-woz
          ports:
            - containerPort: 8080
              name: http
