apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tn-imx-imx
resources:
  - ../../base

images:
  - name: imx-brp-bevragen-mock
    newName: ghcr.io/brp-api/haal-centraal-brp-bevragen-gba-mock
    newTag: 2.0.8
  - name: imx-brp-bevragen-proxy
    newName: ghcr.io/brp-api/haal-centraal-brp-bevragen-proxy
    newTag: 2.1.2
  - name: imx-fieldlab
    newName: ghcr.io/imx-org/imx-fieldlab
    newTag: 34a49c55f5278f1b6e6f835520ef3f7e6340ce88
  - name: imx-orchestrate-imxgeo
    newName: ghcr.io/imx-org/orchestrate-imxgeo
    newTag: 50feecbddb675e34249af296ee0e9d8cc6f5c488

patches:
  - target:
      kind: Ingress
      name: imx-opkoopbescherming-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: imx.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: imx.apps.digilab.network
  - target:
      kind: Ingress
      name: imx-brp-bevragen-proxy-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: imx.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: imx.apps.digilab.network
  - target:
      kind: Ingress
      name: imx-orchestrate-imxgeo-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: imx.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: imx.apps.digilab.network
