nameReference:
  - kind: Deployment
    fieldSpecs:
      - kind: HTTPScaledObject
        path: spec/scaleTargetRef/name
  - kind: Service
    fieldSpecs:
      - kind: HTTPScaledObject
        path: spec/scaleTargetRef/service
